import static app.cash.redwood.buildsupport.TargetGroup.CommonWithAndroid

redwoodBuild {
  targets(CommonWithAndroid)
  publishing()
}

apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'org.jetbrains.kotlin.plugin.serialization'
apply plugin: 'dev.drewhamilton.poko'

kotlin {
  sourceSets {
    commonMain {
      dependencies {
        implementation libs.androidx.compose.runtime
        implementation "composelive.androidx.compose.runtime:runtime-annotation:1.12.0-dev01"
        implementation libs.kotlinx.serialization.core
      }
    }
    wasmWasiMain {
      dependencies {
        implementation 'org.jetbrains.compose.runtime:runtime-wasm-wasi:1.12.0-dev01'
      }
    }
    commonTest {
      dependencies {
        implementation libs.kotlin.test
        implementation libs.assertk
      }
    }
  }
}


android {
  namespace = 'app.cash.redwood.runtime'
}

spotless {
  kotlin {
    targetExclude(
      // Apache 2-licensed files from AOSP.
      "src/commonMain/kotlin/app/cash/redwood/Modifier.kt",
    )
  }
}
